parameters = [
  { name = "dev.frontend.catalogue.nldevopsb01_url", value = "http://catalogue-dev.nldevopsb01.online:8080/" },
  { name = "dev.frontend.user.nldevopsb01_url", value = "http://user-dev.nldevopsb01.online:8080/" },
  { name = "dev.frontend.cart.nldevopsb01_url", value = "http://cart-dev.nldevopsb01.online:8080/" },
  { name = "dev.frontend.shipping.nldevopsb01_url", value = "http://shipping-dev.nldevopsb01.online:8080/" },
  { name = "dev.frontend.payment.nldevopsb01_url", value = "http://payment-dev.nldevopsb01.online:8080/" },
  { name = "dev.catalogue.mongodb.nldevopsb01_endpoint", value = "mongodb-dev.nldevopsb01.online" },
  { name = "dev.catalogue.mongodb.nldevopsb01_host", value = "mongodb://mongodb-dev.nldevopsb01.online:27017/catalogue" },
  { name = "dev.user.redis.nldevopsb01_host", value = "REDIS_HOST=redis-dev.nldevopsb01.online" },
  { name = "dev.user.mongodb.nldevopsb01_url", value = "mongodb://mongodb-dev.nldevopsb01.online:27017/users" },
  { name = "dev.cart.redis.nldevopsb01_host", value = "REDIS_HOST=redis-dev.nldevopsb01.online" },
  { name = "dev.cart.catalogue.nldevopsb01_host", value = "CATALOGUE_HOST=catalogue-dev.nldevopsb01.online" },
  { name = "dev.cart.catalogue.nldevopsb01_port", value = "CATALOGUE_PORT=8080" },
  { name = "dev.shipping.mysql.nldevopsb01_endpoint", value = "mysql-dev.nldevopsb01.online" },
  { name = "dev.shipping.mysql.nldevopsb01_db_user", value = "root" },
  { name = "dev.shipping.mysql.nldevopsb01_db_pwd", value = "RoboShop@1" },
  { name = "dev.shipping.cart.nldevopsb01_endpoint", value = "CART_ENDPOINT=cart-dev.nldevopsb01.online:8080" },
  { name = "dev.shipping.mysqldb.nldevopsb01_host", value = "DB_HOST=mysql-dev.nldevopsb01.online" },
  { name = "dev.payment.cart.nldevopsb01_host", value = "CART_HOST=cart-dev.nldevopsb01.online" },
  { name = "dev.payment.cart.nldevopsb01_port", value = "8080" },
  { name = "dev.payment.user.nldevopsb01_host", value = "USER_HOST=user-dev.nldevopsb01.online" },
  { name = "dev.payment.user.nldevopsb01_port", value = "8080" },
  { name = "dev.payment.rabbitmq.nldevopsb01_host", value = "AMQP_HOST=rabbitmq-dev.nldevopsb01.online" },
  { name = "dev.payment.rabbitmq.nldevopsb01_user", value = "roboshop" },
  { name = "dev.payment.rabbitmq.nldevopsb01_pwd", value = "roboshop123" }

]
